In [13]:
pip install numpy pandas sklearn matplotlib statsmodels seaborn

Requirement already satisfied: numpy in c:\users\82104\ok\lib\site-packages (1.23.3)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: pandas in c:\users\82104\ok\lib\site-packages (1.4.4)
Requirement already satisfied: sklearn in c:\users\82104\ok\lib\site-packages (0.0)
Requirement already satisfied: matplotlib in c:\users\82104\ok\lib\site-packages (3.6.0)
Requirement already satisfied: statsmodels in c:\users\82104\ok\lib\site-packages (0.13.2)
Requirement already satisfied: seaborn in c:\users\82104\ok\lib\site-packages (0.12.0)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\82104\ok\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\82104\ok\lib\site-packages (from pandas) (2022.2.1)
Requirement already satisfied: scikit-learn in c:\users\82104\ok\lib\site-packages (from sklearn) (1.1.2)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\82104\ok\lib\site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\82104\ok\lib\site-packages (from matplotlib) (4.37.3)
Requirement already satisfied: cycler>=0.10 in c:\users\82104\ok\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: packaging>=20.0 in c:\users\82104\ok\lib\site-packages (from matplotlib) (21.3)
Requirement already satisfied: pillow>=6.2.0 in c:\users\82104\ok\lib\site-packages (from matplotlib) (9.2.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\82104\ok\lib\site-packages (from matplotlib) (1.0.5)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\82104\ok\lib\site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: patsy>=0.5.2 in c:\users\82104\ok\lib\site-packages (from statsmodels) (0.5.2)
Requirement already satisfied: scipy>=1.3 in c:\users\82104\ok\lib\site-packages (from statsmodels) (1.9.1)
Requirement already satisfied: six>=1.5 in c:\users\82104\ok\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\82104\ok\lib\site-packages (from scikit-learn->sklearn) (3.1.0)
Requirement already satisfied: joblib>=1.0.0 in c:\users\82104\ok\lib\site-packages (from scikit-learn->sklearn) (1.2.0)

WARNING: You are using pip version 20.2.3; however, version 22.2.2 is available.
You should consider upgrading via the 'C:\Users\82104\ok\Scripts\python.exe -m pip install --upgrade pip' command.

In [14]:
import os
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn import metrics
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import itertools
import time
import statsmodels.api as sm
import statsmodels.formula.api as smf
import seaborn as sns

In [15]:
import sys
print(sys.version)

3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]

In [16]:
boston = pd.read_csv("C:\Users\82104\Desktop\data")

In [17]:
boston

,AGE,B,RM,CRIM,DIS,INDUS,LSTAT,NOX,PTRATIO,RAD,ZN,TAX,CHAS,Target
0,65.2,396.90,6.575,0.00632,4.0900,2.31,4.98,0.538,15.3,1,18.0,296,0,24.0
1,78.9,396.90,6.421,0.02731,4.9671,7.07,9.14,0.469,17.8,2,0.0,242,0,21.6
2,61.1,392.83,7.185,0.02729,4.9671,7.07,4.03,0.469,17.8,2,0.0,242,0,34.7
3,45.8,394.63,6.998,0.03237,6.0622,2.18,2.94,0.458,18.7,3,0.0,222,0,33.4
4,54.2,396.90,7.147,0.06905,6.0622,2.18,5.33,0.458,18.7,3,0.0,222,0,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,69.1,391.99,6.593,0.06263,2.4786,11.93,9.67,0.573,21.0,1,0.0,273,0,22.4
502,76.7,396.90,6.120,0.04527,2.2875,11.93,9.08,0.573,21.0,1,0.0,273,0,20.6
503,91.0,396.90,6.976,0.06076,2.1675,11.93,5.64,0.573,21.0,1,0.0,273,0,23.9
504,89.3,393.45,6.794,0.10959,2.3889,11.93,6.48,0.573,21.0,1,0.0,273,0,22.0
505,80.8,396.90,6.030,0.04741,2.5050,11.93,7.88,0.573,21.0,1,0.0,273,0,11.9